
volumes:
  db-data:

services:

  server:
    container_name: gopher
    image: gopher:latest
    depends_on:
      - db
    restart: always
    ports:
     - 5000:5000

  db:
    container_name: mongodb
    image: mongo
    restart: always
    command: [--auth]
    environment:
      MONGODB_INITDB_ROOT_USERNAME: ${DATABASE_ROOT_USER}
      MONGODB_INITDB_ROOT_PASSWORD: ${DATABASE_ROOT_PASS}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASS: ${DATABASE_PASS}
    volumes:
      - db-data:/data/db
      - ./db-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    healthcheck:
        test: "echo 'db.runCommand(\"ping\").ok' | mongosh ${DATABASE_HOST}:${DATABASE_PORT}/test --quiet"
        interval: 30s
        timeout: 5s
        retries: 5
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
