
volumes:
  db-data:
  pgadmin-data:

services:

  server:
    container_name: gin
    image: gin:latest
    depends_on:
      - db
    restart: always
    ports:
     - 5000:5000

  db:
    container_name: pg
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -d ${DATABASE_NAME} -U ${DATABASE_USER}"]
        interval: 30s
        timeout: 5s
        retries: 5
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"

  admin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - db
    restart: always
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DATABASE_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DATABASE_ADMIN_PASS}
    ports:
      - "5050:80"
